### ISSUE TITLE
Authentication error on few Android devices, But works fine on others

### ISSUE THREAD

**Issue by undali** [googleapis/java-pubsub#1438]
#### Environment details
API: pubsub
OS: Android 9
Java: 8
Version: 1.121.1

#### Steps to reproduce

 Unfortunately I couldn't reproduce this issue other than two android device.

#### Code example

```java
        TopicName topicName = TopicName.of(projectId, topicId);
        String jsonCred =  "{\n" +
            "  \"type\": \"service_account\",\n" +
            "  \"project_id\": \"fchat-5e516\",\n" +
            ................................................
            ................................................
            ................................................
            "  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n" +
            "  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n" +
            "  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n" +
            "  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/chat-test%40fchat-5e516.iam.gserviceaccount.com\"\n" +
            "}";
  
        Publisher publisher = null;
        try {
            GoogleCredentials credentials =
                    GoogleCredentials.fromStream(new ByteArrayInputStream(jsonCred.getBytes()));
            publisher = Publisher.newBuilder(topicName)
                    .setCredentialsProvider(FixedCredentialsProvider.create(credentials))
                    .build();

            String message = "Hello World!";
            ByteString data = ByteString.copyFromUtf8(message);
            PubsubMessage pubsubMessage = PubsubMessage.newBuilder().setData(data).build();

            // Once published, returns a server-assigned message id (unique within the topic)
            ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
            String messageId = messageIdFuture.get();
            Log.i(TAG, "Published message ID: " + messageId);
        }
```

#### Stack trace
```
2022-12-03 07:32:02.396 4900-5331/com.anyconnect.camera_app W/System.err: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
2022-12-03 07:32:02.397 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
2022-12-03 07:32:02.398 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
2022-12-03 07:32:02.398 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:55)
2022-12-03 07:32:02.398 4900-5331/com.anyconnect.camera_app W/System.err:     at com.anyconnect.service.GenericPubSubClient.publisherExample(GenericPubSubClient.java:81)
2022-12-03 07:32:02.398 4900-5331/com.anyconnect.camera_app W/System.err:     at com.anyconnect.service.GenericPubSubClient.lambda$new$0$GenericPubSubClient(GenericPubSubClient.java:162)
2022-12-03 07:32:02.398 4900-5331/com.anyconnect.camera_app W/System.err:     at com.anyconnect.service.-$$Lambda$GenericPubSubClient$KCAqSsoQ6ZQXyfeonWG6CkrryNk.run(Unknown Source:2)
2022-12-03 07:32:02.399 4900-5331/com.anyconnect.camera_app W/System.err:     at java.lang.Thread.run(Thread.java:764)
2022-12-03 07:32:02.400 4900-5331/com.anyconnect.camera_app W/System.err: Caused by: com.google.api.gax.rpc.UnauthenticatedException: io.grpc.StatusRuntimeException: UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
2022-12-03 07:32:02.400 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:116)
2022-12-03 07:32:02.400 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:98)
2022-12-03 07:32:02.400 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:67)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1132)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
2022-12-03 07:32:02.401 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:535)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:471)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:435)
2022-12-03 07:32:02.402 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:468)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
2022-12-03 07:32:02.403 490-1870/? V/u-blox: CUbxGpsState::writeUbxCfgMsg: Sent CFG-MSG id=F0-02 (enable NMEA-GSA)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2022-12-03 07:32:02.403 4900-5331/com.anyconnect.camera_app W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2022-12-03 07:32:02.404 4900-5331/com.anyconnect.camera_app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2022-12-03 07:32:02.404 4900-5331/com.anyconnect.camera_app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2022-12-03 07:32:02.404 4900-5331/com.anyconnect.camera_app W/System.err: 	... 1 more

```

Interesting thing is, this same code runs successfully on some android devices. But it gives error on few android devices.

Is there any cache/cookie in file system stored by pub sub that needs to be deleted?

I've tried the solution described here https://github.com/googleapis/java-pubsub/issues/930#issuecomment-990037784
, in that case `publisher.publish(pubsubMessage)` hangs forever.

**Comment by undali** [comment]
It seems like related to timezone. If timezone is changed manually this issue appears.
