### ISSUE TITLE
Missing some dependencies or default config

### ISSUE THREAD

**Issue by owen2** [googleapis/java-pubsub#1481]
Following the guide here: https://cloud.google.com/pubsub/docs/reference/libraries#use

On JDK 11.

When I try to publish to a topic, I get an exception like this:

After some frustration, I found that installing `grpc-core` to my maven dependencies fixed the issue. 

`SEVERE: [Channel<1>: (pubsub.googleapis.com:443)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.IllegalStateException: Could not find policy 'pick_first'. Make sure its implementation is either registered to LoadBalancerRegistry or included in META-INF/services/io.grpc.LoadBalancerProvider from your jar files.
    at io.grpc.internal.AutoConfiguredLoadBalancerFactory$AutoConfiguredLoadBalancer.<init>(AutoConfiguredLoadBalancerFactory.java:94)
    at io.grpc.internal.AutoConfiguredLoadBalancerFactory.newLoadBalancer(AutoConfiguredLoadBalancerFactory.java:61)
    at io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:412)
    at io.grpc.internal.ManagedChannelImpl$RealChannel$2.run(ManagedChannelImpl.java:981)
    at io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
    at io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
    at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:978)
    at com.google.api.gax.grpc.GrpcChannelUUIDInterceptor.interceptCall(GrpcChannelUUIDInterceptor.java:52)
    at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
    at com.google.api.gax.grpc.GrpcHeaderInterceptor.interceptCall(GrpcHeaderInterceptor.java:80)
    at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
    at com.google.api.gax.grpc.GrpcMetadataHandlerInterceptor.interceptCall(GrpcMetadataHandlerInterceptor.java:54)
    at io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156)
    at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:920)
    at io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63)
    at com.google.api.gax.grpc.ChannelPool$AffinityChannel.newCall(ChannelPool.java:514)
    at com.google.api.gax.grpc.ChannelPool.newCall(ChannelPool.java:143)
    at com.google.api.gax.grpc.GrpcClientCalls.newCall(GrpcClientCalls.java:99)
    at com.google.api.gax.grpc.GrpcDirectCallable.futureCall(GrpcDirectCallable.java:60)
    at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:65)
    at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
    at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87)
    at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
    at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
    at com.google.api.gax.tracing.TracedBatchingCallable.futureCall(TracedBatchingCallable.java:82)
    at com.google.api.gax.rpc.BatchingCallable.futureCall(BatchingCallable.java:79)
    at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
    at com.google.cloud.pubsub.v1.Publisher.publishCall(Publisher.java:456)
    at com.google.cloud.pubsub.v1.Publisher.publishOutstandingBatch(Publisher.java:522)
    at com.google.cloud.pubsub.v1.Publisher.publishAllWithoutInflight(Publisher.java:426)
    at com.google.cloud.pubsub.v1.Publisher.access$1400(Publisher.java:91)
    at com.google.cloud.pubsub.v1.Publisher$2.run(Publisher.java:353)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
ERROR 2023-02-17 18:55:56,305 - Error during processing of request: 'Waited 5 seconds (plus 320277 nanoseconds delay) for com.google.api.core.AbstractApiFuture$InternalSettableFuture@34c6974[status=PENDING]'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.util.concurrent.TimeoutException: Waited 5 seconds (plus 320277 nanoseconds delay) for com.google.api.core.AbstractApiFuture$InternalSettableFuture@34c6974[status=PENDING]
    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527)
    at ...`

I'm using this chunk to install the pub sub library: 
`<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>libraries-bom</artifactId>
      <version>26.1.5</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-pubsub</artifactId>
  </dependency>

</dependencies>`

**Comment by maitrimangal** [comment]
Hi - are you using the correct google-cloud-libraries BOM (https://cloud.google.com/java/docs/bom)? And can you share the dependency tree.

**Comment by NuwanSameera** [comment]
@owen2 I resolved it with maven shade plugin and service files merge transform.

Added detailed answer to my question in
https://stackoverflow.com/a/76478906/5607943

Hope this help.

**Comment by maitrimangal** [comment]
thanks Nuwan! @owen2 please let us know if that solves your problem, and we can close this issue.

**Comment by NuwanSameera** [comment]
@maitrimangal my issue resolved with this

**Comment by maitrimangal** [comment]
Hi closing this ticket! please let us know by opening a new ticket if this problem still exists for you!
