### ISSUE TITLE
PublisherExample fails

### ISSUE THREAD

**Issue by jheth** [googleapis/java-pubsub#1648]
#### Environment details

1. General, Core
2. OS type and version: macOS  Ventura 13.3.1
3. Java version: 8
4.  version(s):

#### Steps to reproduce

  1. Click Run

#### Code example

https://github.com/googleapis/java-pubsub/blob/HEAD/samples/snippets/src/main/java/pubsub/PublisherExample.java

```java
// example
import com.google.api.core.ApiFuture;
import com.google.cloud.pubsub.v1.Publisher;
import com.google.protobuf.ByteString;
import com.google.pubsub.v1.PubsubMessage;
import com.google.pubsub.v1.TopicName;
import java.io.IOException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;

public class PublisherExample {
	public static void main(String... args) throws Exception {
		// TODO(developer): Replace these variables before running the sample.
		String projectId = "sample-id";
		String topicId = "sample-topic";

		publisherExample(projectId, topicId);
	}

	public static void publisherExample(String projectId, String topicId)
		throws IOException, ExecutionException, InterruptedException {
		TopicName topicName = TopicName.of(projectId, topicId);

		Publisher publisher = null;
		try {
			// Create a publisher instance with default settings bound to the topic
			publisher = Publisher.newBuilder(topicName).build();

			String message = "Hello World!";
			ByteString data = ByteString.copyFromUtf8(message);
			PubsubMessage pubsubMessage = PubsubMessage.newBuilder()
				.setData(data)
				.build();

			// Once published, returns a server-assigned message id (unique within the topic)
			ApiFuture<String> messageIdFuture = publisher.publish(pubsubMessage);
			String messageId = messageIdFuture.get(); // <-- this line fails
			System.out.println("Published message ID: " + messageId);
		} finally {
			if (publisher != null) {
				// When finished with the publisher, shutdown to free up resources.
				publisher.shutdown();
				publisher.awaitTermination(1, TimeUnit.MINUTES);
			}
		}
	}
}

```

#### Stack trace
```

Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap$Builder.buildKeepingLast()Lcom/google/common/collect/ImmutableMap;
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:481)
	at com.google.api.core.AbstractApiFuture.get(AbstractApiFuture.java:53)
	at PublisherExample.publisherExample(PublisherExample.java:44)
	at PublisherExample.main(PublisherExample.java:23)
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableMap$Builder.buildKeepingLast()Lcom/google/common/collect/ImmutableMap;
	at com.google.api.gax.rpc.RequestParamsBuilder.build(RequestParamsBuilder.java:94)
	at com.google.cloud.pubsub.v1.stub.GrpcPublisherStub.lambda$new$2(GrpcPublisherStub.java:266)
	at com.google.api.gax.rpc.RequestUrlParamsEncoder.encode(RequestUrlParamsEncoder.java:74)
	at com.google.api.gax.grpc.GrpcUnaryRequestParamCallable.futureCall(GrpcUnaryRequestParamCallable.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable.futureCall(GrpcExceptionCallable.java:64)
	at com.google.api.gax.rpc.AttemptCallable.call(AttemptCallable.java:87)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:63)
	at com.google.api.gax.rpc.RetryingCallable.futureCall(RetryingCallable.java:41)
	at com.google.api.gax.tracing.TracedBatchingCallable.futureCall(TracedBatchingCallable.java:82)
	at com.google.api.gax.rpc.BatchingCallable.futureCall(BatchingCallable.java:79)
	at com.google.api.gax.rpc.UnaryCallable$1.futureCall(UnaryCallable.java:126)
	at com.google.cloud.pubsub.v1.Publisher.publishCall(Publisher.java:456)
	at com.google.cloud.pubsub.v1.Publisher.publishOutstandingBatch(Publisher.java:522)
	at com.google.cloud.pubsub.v1.Publisher.publishAllWithoutInflight(Publisher.java:426)
	at com.google.cloud.pubsub.v1.Publisher.access$1400(Publisher.java:91)
	at com.google.cloud.pubsub.v1.Publisher$2.run(Publisher.java:353)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)


```

#### External references such as API reference guides

https://github.com/googleapis/java-pubsub/blob/HEAD/samples/snippets/src/main/java/pubsub/PublisherExample.java

**Comment by jheth** [comment]
I was using an older version of guava.
