### ISSUE TITLE
Subscriber addListnener() method/example doesn't WAI

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/java-pubsub#1653]
#### Environment details

1. Specify the API at the beginning of the title.
2. OS type and version: MacOS 13.4.1 (22F82)
3. Java version: 
    ```
    tianzi 13:57 snippets % java --version                               (listener)
    openjdk 17.0.7 2023-04-18
    OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
    OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)
    ```
5.  version(s): google-cloud-pubsub-1.123.11

#### Steps to reproduce

  1. run `cd samples/snippets`
  2. `vim src/main/java/pubsub.SubscribeWithErrorListenerExample.java` to use my own project and subscription ID in Line 35-36, and update timeout to ≥10 minutes in Line 82
  3. run `mvn clean compile exec:java -Dexec.mainClass=SubscribeWithErrorListenerExample`
  4. after getting some messages, deliberately turn off WiFi to cause an UNAVAILABLE error
  5. observe error stacktrace getting printed in the terminal (copied and pasted below)
  6. turn on WiFi. expecting messages to continue pouring in, but the subscriber doesn't seem to restart. 

#### Code example

Exactly as shown in https://github.com/googleapis/java-pubsub/blob/main/samples/snippets/src/main/java/pubsub/SubscribeWithErrorListenerExample.java

#### Stack trace

```
Data: {"ride_id":"b63ce255-18ce-47ae-8481-2a00f89baebe","point_idx":64,"latitude":40.770320000000005,"longitude":-73.96229000000001,"timestamp":"2023-07-05T00:58:56.25334-04:00","meter_reading":3.4385092,"meter_increment":0.053726707,"ride_status":"enroute","passenger_count":1}
Id: 8638550338603612
Data: {"ride_id":"f8d8b70a-9e92-4abd-8905-518d71553ec5","point_idx":302,"latitude":40.710750000000004,"longitude":-73.98156,"timestamp":"2023-07-05T00:58:56.25308-04:00","meter_reading":5.544531,"meter_increment":0.018359374,"ride_status":"enroute","passenger_count":1}
Jul 11, 2023 1:39:01 PM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<1>: (pubsub.googleapis.com:443)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host pubsub.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: pubsub.googleapis.com: nodename nor servname provided, or not known
at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: pubsub.googleapis.com: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 6 more
}
Jul 11, 2023 1:39:17 PM com.google.cloud.pubsub.v1.StreamingSubscriberConnection$2 onFailure
WARNING: failed to send operations
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host pubsub.googleapis.com
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Unable to resolve host pubsub.googleapis.com
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 17 more
Caused by: java.lang.RuntimeException: java.net.UnknownHostException: pubsub.googleapis.com: nodename nor servname provided, or not known
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	... 3 more
Caused by: java.net.UnknownHostException: pubsub.googleapis.com: nodename nor servname provided, or not known
	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
	... 6 more
```

#### External references such as API reference guides

- Is this code sample written correctly? 
- Is `addListener()` working correctly?
- what is considered "unrecoverable failures or "permanent errors"? are they the same as non-retryable errors (https://cloud.google.com/pubsub/docs/reference/error-codes)? 
- If turning the WiFi on and off is not creating an unrecoverable error, what should be considered an unrecoverable error? how do I test? 
- Should this code example be revised and model something like this? https://github.com/googleapis/java-pubsub-group-kafka-connector/blob/main/src/main/java/com/google/pubsub/kafka/source/CloudPubSubGRPCSubscriber.java

**Comment by maitrimangal** [comment]
Ack, taking a look

**Comment by maitrimangal** [comment]
Hi, I tried to replicate the issue, and was unable to do so. AKA the subscribe was working as expected.
Here are the steps I tried, if there is something different then please correct me:

1. Created topic, and subscriber in pubsub
2. Started subscriber
3. Published messages 'a','b','c' to topic and observed that subscriber had received the message correctly
4. Turned off the wifi
5. Published messages 'd','e' to topic
6. Restarted subscriber
7. Immediately saw that 'd','e' was received by the subscriber.

Attaching screenshots in internal bug to follow along!
