### ISSUE TITLE
sync pull causes DeadlineExceededException

### ISSUE THREAD

**Issue by saturnism** [googleapis/java-pubsub#189]
doing a sync pull on a subscription, and if there is no message, it throws `DeadlineExceededException`.  Usually, if a pull times out, it would just return null.  Also, pull wait time interval is usually configuration, how can this be configured?

```
Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 4.978775875s. [buffered_nanos=291856840, buffered_nanos=331252614, remote_addr=pubsub.googleapis.com/172.217.12.138:443]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:51)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:522)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:497)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$1CloseInContext.runInContext(ClientCallImpl.java:416)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	... 6 more
```

**Comment by kamalaboulhosn** [comment]
When you say "usually, if a pull times out, it would just return null," what do you mean? As in, that used to be the behavior or that is the behavior you expect?

**Comment by saturnism** [comment]
> When you say "usually, if a pull times out, it would just return null," what do you mean? As in, that used to be the behavior or that is the behavior you expect?

IIRC, it was the old behavior when the client library had the idiomatic APIs. It's also the behavior for most of the other messaging APIs other than Pub/Sub.

**Comment by elefeint** [comment]
We have a user issue that is related to this -- Pub/Sub timing out on a health check, which performs a synchronous pull with `returnImmediately=true`: spring-cloud/spring-cloud-gcp#2628.

What should be done here -- should the user open a support ticket for abnormally high pull latency, or is this a normal scenario, and we should adjust the health check indicator to ignore DEADLINE_EXCEEDED? It feels wrong to ignore, since a too-long latency is a valid indicator of a service problem.

**Comment by meredithslota** [comment]
I'm going to assign this to @anguillanneuf to discuss with Elena and see if we can figure out next steps.

**Comment by brachipa** [comment]
For me it happens when there is no messages available (v1.90.0)

**Comment by anguillanneuf** [comment]
Both gcloud and Python will just return nothing or null if there are no messages. The Java client library behaves somewhat differently. If we do want to change it back, this would be a feature request. FYI - @mmicatka

**Comment by anguillanneuf** [comment]
AFAIK, the current sample no longer returns `DeadlineExceededException` when there are no messages to be pulled. It fails immediately. Updating the sample to handle the no `ackId` case. 

```sh
Exception in thread "main" com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: You have not specified an ack ID in the request.
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:47)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1277)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:808)
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:564)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:534)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:562)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:743)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:722)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57)
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112)
		at pubsub.SubscribeSyncExample.subscribeSyncExample(SubscribeSyncExample.java:80)
		at pubsub.SubscribeSyncExample.main(SubscribeSyncExample.java:43)
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: You have not specified an ack ID in the request.
	at io.grpc.Status.asRuntimeException(Status.java:535)
	... 10 more
```
