### ISSUE TITLE
Getting NoClassDefFoundError exception while initializing publisher instance

### ISSUE THREAD

**Issue by namansg** [googleapis/java-pubsub#393]
I am trying to publish to PubSub topic using this library. I am using gradle and have added following dependency:
```
compile 'com.google.cloud:google-cloud-pubsub:1.108.4'
```

However while initializing publisher instance as in the following line:
```
publisher = Publisher.newBuilder(topicName).build();
```

I am getting NoClassDefFoundError exception:

```
java.lang.NoClassDefFoundError: com/google/pubsub/v1/DetachSubscriptionRequest
	at com.google.cloud.pubsub.v1.stub.GrpcPublisherStub.<clinit>(GrpcPublisherStub.java:163) ~[google-cloud-pubsub-1.108.4.jar:1.108.4]
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:188) ~[google-cloud-pubsub-1.108.4.jar:1.108.4]
	at com.google.cloud.pubsub.v1.Publisher.<init>(Publisher.java:88) ~[google-cloud-pubsub-1.108.4.jar:1.108.4]
	at com.google.cloud.pubsub.v1.Publisher$Builder.build(Publisher.java:821) ~[google-cloud-pubsub-1.108.4.jar:1.108.4]
	at com.sharechat.platform.gateway.utils.AsyncTasks.publishMessage(AsyncTasks.java:53) ~[classes/:na]
	at com.sharechat.platform.gateway.utils.AsyncTasks$$FastClassBySpringCGLIB$$df388a10.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_192]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_192]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_192]
Caused by: java.lang.ClassNotFoundException: com.google.pubsub.v1.DetachSubscriptionRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_192]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_192]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_192]
	... 15 common frames omitted
```

Can you please tell if I am missing something here?

Thanks

**Comment by hannahrogers-google** [comment]
Hi @namansg, happy to help. It is possible that you are running into a dependency issue. Are you using a Google Cloud Libraries [BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) for dependency management?
