### ISSUE TITLE
I Am facing an error where my call is not reaching the gcp services from my oracle weblogic , where we could not able to identify the issue for what reason the request are getting blocked to reach the gcp services. here the error we are getting when we try with pubsub

### ISSUE THREAD

**Issue by harisatyanarayana-php** [googleapis/java-pubsub#625]
I Am facing an error where my call is not reaching the gcp services from my oracle weblogic , where we could not able to identify the issue for what reason the request are getting blocked to reach the gcp services. here the error we are getting when we try with pubsub 

 Caused By: javax.net.ssl.SSLHandshakeException: General SSLEngine problem

        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)

        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)

        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)

        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)

        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)

        at java.security.AccessController.doPrivileged(Native Method)

        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)

        at weblogic.socket.JSSEFilterImpl.doTasks(JSSEFilterImpl.java:205)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:111)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:75)

        at weblogic.socket.JSSESocket.startHandshake(JSSESocket.java:219)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:563)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:534)

        at weblogic.net.http.HttpsURLConnection.connect(HttpsURLConnection.java:248)

        at weblogic.net.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:341)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)

        at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:454)

        at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:164)

        at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:149)

        at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:103)

        at com.google.auth.Credentials$1.run(Credentials.java:92)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

Caused By: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)

        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

        at sun.security.validator.Validator.validate(Validator.java:260)

        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)

        at weblogic.security.SSL.jsseadapter.JaTrustManager.checkServerTrusted(JaTrustManager.java:128)

        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:936)

        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)

        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)

        at java.security.AccessController.doPrivileged(Native Method)

        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)

        at weblogic.socket.JSSEFilterImpl.doTasks(JSSEFilterImpl.java:205)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:111)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:75)

        at weblogic.socket.JSSESocket.startHandshake(JSSESocket.java:219)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:563)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:534)

        at weblogic.net.http.HttpsURLConnection.connect(HttpsURLConnection.java:248)

        at weblogic.net.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:341)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)

        at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:454)

        at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:164)

        at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:149)

        at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:103)

        at com.google.auth.Credentials$1.run(Credentials.java:92)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

Caused By: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)

        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)

        at sun.security.validator.Validator.validate(Validator.java:260)

        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)

        at weblogic.security.SSL.jsseadapter.JaTrustManager.checkServerTrusted(JaTrustManager.java:128)

        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:936)

        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)

        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)

        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)

        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)

        at java.security.AccessController.doPrivileged(Native Method)

        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)

        at weblogic.socket.JSSEFilterImpl.doTasks(JSSEFilterImpl.java:205)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:111)

        at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:75)

        at weblogic.socket.JSSESocket.startHandshake(JSSESocket.java:219)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:563)

        at weblogic.net.http.HttpsClient.New(HttpsClient.java:534)

        at weblogic.net.http.HttpsURLConnection.connect(HttpsURLConnection.java:248)

        at weblogic.net.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:341)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)

        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)

        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)

        at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:454)

        at com.google.auth.oauth2.OAuth2Credentials.refresh(OAuth2Credentials.java:164)

        at com.google.auth.oauth2.OAuth2Credentials.getRequestMetadata(OAuth2Credentials.java:149)

        at com.google.auth.Credentials.blockingGetToCallback(Credentials.java:103)

        at com.google.auth.Credentials$1.run(Credentials.java:92)

        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

**the code that we are using is below :** 

ProjectSubscriptionName subscriptionName = ProjectSubscriptionName.of(projectId, subscriptionId);

		// Instantiate an asynchronous message receiver.
		MessageReceiver receiver = (PubsubMessage message, AckReplyConsumer consumer) -> {
			// Handle incoming message, then ack the received message.

			 //consumer.ack();

			byte[] protobuf = message.getData().toByteArray();
			
			String string = new String(protobuf);
	        System.out.println(string);

};

CredentialsProvider crede = FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(new FileInputStream("credentail.json")));
		  //System.out.println(crede);
		subscriber = Subscriber.newBuilder(subscriptionName, receiver).setCredentialsProvider(crede).build();
		// Start the subscriber.
		
		System.out.println(subscriber.state());
		
		subscriber.startAsync().awaitRunning();
		System.out.printf("Listening for messages on %s:\n", subscriptionName.toString());
		System.out.println(subscriber.state());
		
		subscriber.awaitTerminated();
		System.out.println(subscriber.state());

_Originally posted by @harisatyanarayana-php in https://github.com/googleapis/java-pubsub/issues/273#issuecomment-825420485_

**Comment by harisatyanarayana-php** [comment]
any update on this issue we really looking forward for your reply

**Comment by hannahrogers-google** [comment]
This appears to be an issue with Credentials that is likely not specific to Pub/Sub.  Can you provide more information on the environment that you are running in?  I am assuming you are not running inside a Google Cloud environment, and I am assuming your are running in an environment with no service account attached?

How was the 'credentials.json' file obtained? Was the service account key downloaded after creating a service account?

**Comment by harisatyanarayana-php** [comment]
hi @hannahrogers-google  am running this service as ear application , in oracle WebLogic 12c , here is my code that I am running in WebLogic, as per questions you have asked on the service key , I have taken the service key after the service account creation only and second one is we are not running the services in google cloud we are running outside out i.e. on our own WebLogic server.  Here one strange thing is the same code is working as jar file in the linux server , but not working in weblogic side , we neeed your guide to find the solution , will pubsub librabry will work for the weblogic or not .

BELOW IS THECODE THAT WE RUNNING IN THE WEBLOGIC 12C WHERE ARE NOT GETTING ANY MESSAGES FROM PUBSUB 




protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		PrintWriter out = response.getWriter();

		
		  String projectId = "******"; 
		  String subscriptionId ="******";
		

		ProjectSubscriptionName subscriptionName = ProjectSubscriptionName.of(projectId, subscriptionId);

		
		MessageReceiver receiver = (PubsubMessage message, AckReplyConsumer consumer) -> {
			

			 consumer.ack();

			byte[] protobuf = message.getData().toByteArray();
			
			
			String string = new String(protobuf);
	        System.out.println(string);
			
			
	       
			
			
		};

		Subscriber subscriber = null;
		
		 
		CredentialsProvider crede = FixedCredentialsProvider.create(ServiceAccountCredentials.fromStream(new FileInputStream("credentails.json")));
		  System.out.println(crede);
		subscriber = Subscriber.newBuilder(subscriptionName, receiver).setCredentialsProvider(crede).build();
		// Start the subscriber.
		subscriber.startAsync().awaitRunning();
		System.out.printf("Listening for messages on %s:\n", subscriptionName.toString());
		// Allow the subscriber to run for 30s unless an unrecoverable error occurs.
		//subscriber.awaitTerminated();
		try {
			subscriber.stopAsync().awaitTerminated(5, TimeUnit.SECONDS);
		} catch (TimeoutException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		
		out.println(HTML_START + "<h2>Hi There!</h2><br/><h3>" + HTML_END);
		
		
		
		
	}

**Comment by harisatyanarayana-php** [comment]
hi @hannahrogers-google  when i run my code in the oracle  WebLogic 12c i was getting like below , where messages are not getting displayed also 

<May 6, 2021 2:47:51,788 PM IST> <Warning> <Security> <BEA-090504> <Certificate chain received from oauth2.googleapis.com - ***.***.**.**(ip address) failed hostname verification check. Certificate contained upload.video.google.com but check expected oauth2.googleapis.com>

**Comment by harisatyanarayana-php** [comment]
Please give us someupdate we really looking for your help

**Comment by hannahrogers-google** [comment]
I am unfamiliar with weblogic - have you opened a customer support issue with weblogic to ensure that SSL is properly configured? They might also be able to provide some more details on the SunCertPathBuilderException that you are seeing.

Re the following error:

<May 6, 2021 2:47:51,788 PM IST> <Certificate chain received from oauth2.googleapis.com - ...(ip address) failed hostname verification check. Certificate contained upload.video.google.com but check expected oauth2.googleapis.com>

As a sanity check, have you tried disabling host name verification?

**Comment by harisatyanarayana-php** [comment]
We have now ssl certification problem also @hannahrogers-google  but still we are not receiving messages from weblogic if we deploy our code , but if we are running that same code in tomcat it is working fine .so would require your suggestion , does weblogic supports pubsub apis or not .

**Comment by hannahrogers-google** [comment]
Now that the SSL problem has been resolved are you seeing any other error when running the subscriber? Does the subscriber fail, or does all appear to be running ok (other than not receiving messages)?

**Comment by harisatyanarayana-php** [comment]
I am not getting any error other than not receiving the messages from the subscription from the WebLogic side
