### ISSUE TITLE
Occasional NotFoundException when attempting to pull messages from subscription immediately after creation. 

### ISSUE THREAD

**Issue by jtanningbed** [googleapis/java-pubsub#81]
I am utilizing this library as part of an effort to build out a test automation framework. The basic aim is to create a wrapper class around the already existing Subscriber functionality to abstract out the lower level details and make creating, polling, and deleting subscriptions as easy as possible. A plausible test scenario is as follows: 

- Create a pull subscription on a preexisting topic and project
- Create an instance of the subscriber and start
- Trigger some workflow/task that should publish to subscribed topic
- Pull messages from the subscriber and validate the response
- Delete the subscription and cleanup

Java version: 1.8.0_201
google-cloud-pubsub version: 1.102.1

With my implementation, I am able to create the pull subscription, start the subscription, receive x incoming messages, stop, and delete the subscription. However, it seems like something is off because occasionally I will receive a NotFoundException due to the resource (projects/{project}/subscriptions/{subscription}) not being found. My immediate thought was that the resource is sometimes unavailable because I am not giving it any time in between creating and starting the subscription, and thus it's possible the subscription had not completed the creation process before I started polling. However, it seems like this issue is linked more to the repetition of the workflow, rather than the time between calls. In other words, I am more likely to see this error every _other_ execution, as opposed to it being related to the amount of time I wait after creating the subscription to begin polling. I'm not a java expert and have referenced a lot of examples to implement my wrapper class so I'm afraid that I'm doing things against the general paradigms that this library was built upon. 

#### Code example
Things to note about my naive PubSubSubscriber implementation
- One instance of PubSubSubscriber per subscription. Allow for multiple instances to be running asynchronously
- Each instance of PubSubSubscriber has its own Subscriber attribute, and a queue (I'm using LinkedBlockingDeque<PubsubMessage>). I've read that it's important to use a queue that is thread safe but I'm not exactly sure how much this matters if I'm creating a new instance of it per instance of the PubSubSubscriber. Is it simply incorrect to be creating an instance of LinkedBlockingDeque per PubSubSubscriber if the queue is already designed to be thread-safe?
- I have implemented a static method in this class called createPullSubscription(). Since it is static, it doesn't require an instance to be created in order to call this method; does that cause issues if I create an instance after creating the pull subscription so that I can subscribe and pull from the newly created subscription?

Basic constructor looks something like this:
```java
  public PubSubSubscriber(String projectId, String subscriptionId)  {
    this.PROJECT_ID = projectId;
    this.SUBSCRIPTION_ID = subscriptionId;
    this.messages = new LinkedBlockingDeque<>();
      ProjectSubscriptionName subscriptionName = ProjectSubscriptionName
          .of(this.PROJECT_ID, this.SUBSCRIPTION_ID);

    this.subscriber = Subscriber.newBuilder(subscriptionName,
          ((PubsubMessage message, AckReplyConsumer consumer) -> {
            this.messages.offer(message);
            consumer.ack();
            })
          )
        .build();
```

The createPullSubscription method (which resides in the same class) looks like:
```java
  public static void createPullSubscription(String projectId, String topicId, String subscriptionId)
      throws IOException {

    ProjectTopicName topicName = ProjectTopicName.of(projectId, topicId);
    ProjectSubscriptionName subscriptionName = ProjectSubscriptionName.of(
        projectId, subscriptionId);

    try (SubscriptionAdminClient subscriptionAdminClient = SubscriptionAdminClient.create()) {
      Subscription subscription = subscriptionAdminClient.createSubscription(subscriptionName, topicName,
          PushConfig.getDefaultInstance(), 0);
    } catch (ApiException e) {
      System.out.println(e.getStatusCode().getCode());
      System.out.println(e.isRetryable());
    }
```

Test code in main method: 
```
public static void main(String... args) {
  PubSubSubscriber.createPullSubscription("my-project", "my-topic", "my-test-sub");
  PubSubSubscriber ps = new PubSubSubscriber("my-project", "my-test-sub");

  // this simply calls ps.subscriber.startAsync().awaitRunning();
  ps.start();

  // Receive Messages on the subscription based on a key and value to look for (my own method that uses poll())
  JsonArray messages = ps.getMessages("id", testId);

  // this simply calls ps.subscriber.stopAsync().awaitTerminated();
  ps.stop();

  // also my own static method to delete
  PubSubSubscriber.deleteSubscription("my-project", "my-test-sub");
}
```
#### Stack trace
```
Feb 03, 2020 4:40:02 PM com.google.cloud.pubsub.v1.StreamingSubscriberConnection$1 onFailure
SEVERE: terminated streaming with exception
com.google.api.gax.rpc.NotFoundException: com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=projects/my-project/subscriptions/my-test-sub).
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$1.onFailure(StreamingSubscriberConnection.java:238)
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1039)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1165)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:958)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:749)
	at com.google.api.core.AbstractApiFuture$InternalSettableFuture.setException(AbstractApiFuture.java:95)
	at com.google.api.core.AbstractApiFuture.setException(AbstractApiFuture.java:77)
	at com.google.api.core.SettableApiFuture.setException(SettableApiFuture.java:52)
	at com.google.cloud.pubsub.v1.StreamingSubscriberConnection$StreamingPullResponseObserver.onError(StreamingSubscriberConnection.java:174)
	at com.google.api.gax.tracing.TracedResponseObserver.onError(TracedResponseObserver.java:103)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:84)
	at com.google.api.gax.rpc.StateCheckingResponseObserver.onError(StateCheckingResponseObserver.java:86)
	at com.google.api.gax.grpc.GrpcDirectStreamController$ResponseObserverAdapter.onClose(GrpcDirectStreamController.java:149)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:521)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:641)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:529)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:703)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:692)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.api.gax.rpc.NotFoundException: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=projects/my-project/subscriptions/my-test-sub).
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:45)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
	at com.google.api.gax.grpc.ExceptionResponseObserver.onErrorImpl(ExceptionResponseObserver.java:82)
	... 25 more
Caused by: io.grpc.StatusRuntimeException: NOT_FOUND: Resource not found (resource=projects/my-project/subscriptions/my-test-sub).
	at io.grpc.Status.asRuntimeException(Status.java:533)
	... 24 more
```

#### Any additional information below
- The error doesn't occur during instantiation of the class for a new subscription. It occurs when I attempt to pull messages. (`this.messages.poll()`)
- I've tried modifying flow control settings, parallel pull counts, making state checks, etc. Nothing seems to change the outcome. 
- The only "pattern" I've been able to identify is that it rarely happens twice in a row, and it's pretty common for it to happen every other run, but sometimes it will work 2-3 times consecutively before crashing with that error. The resource and project names for the generated subscription have remained unchanged for each run.

Is there something obvious I'm missing here? Is it possible I'm not shutting down threads somehow? I'm using startAsync() and stopAsync() to start and stop and have even tried awaiting for Running/Terminated states. Is there anything else regarding the resource status that I can continuously check for before attempting to connect to a resource to ensure that the resource is available? Any and all help (including ripping apart my naive implementation) is appreciated.

Thanks!

**Comment by hannahrogers-google** [comment]
@jtanningbed, thanks for reaching out about this issue - I will attempt to reproduce the same error and get back to you

**Comment by hannahrogers-google** [comment]
@jtanningbed, I have looked into the issue that you are seeing.  Everytime that you call the createPullSubscription method, it looks like you are using the same subscription name. It is likely that you need to wait for a longer period of time before you delete a subscription and immediately try to re-create that subscription.  Here are a couple of things that you can try:

1) Wait a few minutes between calls to your createPullSubscription method (~3 minutes)
2) Use a different subscription name every time.  The base name can be the same "my-test-sub", but you can then append a unique identifier onto the end of the subscription name each run (timestamp, number that increases on each call, etc.)
