### ISSUE TITLE
No servers found for pubsub.googleapis.com:443

### ISSUE THREAD

**Issue by AnswerNo2** [googleapis/java-pubsub#965]
2022-01-08 05:51:50.035 ERROR [grpc-default-executor-0]  n.d.b.g.c.n.DiscoveryClientNameResolver.resolveInternal:204 - No servers found for pubsub.googleapis.com:443

   2022-01-08 05:51:50.035 ERROR [grpc-default-executor-1]  n.d.b.g.c.n.DiscoveryClientNameResolver.resolveInternal:204 - No servers found for pubsub.googleapis.com:443

   2022-01-08 05:51:50.035 WARN  [grpc-default-executor-1]  i.g.i.ManagedChannelImpl.handleErrorInSyncContext:1489 - [Channel<12>: (pubsub.googleapis.com:443)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for pubsub.googleapis.com:443, cause=null}

   2022-01-08 05:51:50.035 WARN  [grpc-default-executor-0]  i.g.i.ManagedChannelImpl.handleErrorInSyncContext:1489 - [Channel<14>: (pubsub.googleapis.com:443)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for pubsub.googleapis.com:443, cause=null}

**Comment by mmicatka** [comment]
Hi @AnswerNo2, could you provide some more background information around what lead to these errors? Have you been able to replicate the issue?

**Comment by JobsLeeCN** [comment]
I want to know how to solve this question, now I have the same question too.

**Comment by JobsLeeCN** [comment]
>  I have only these logs, I can make sure my google-config-json file is no problem and I can run a demo successfully in the local main method. I have tried many times, and I wonder if it has something to do with the version of some components?
```bash
2022-06-23 19:46:25.929 [grpc-default-executor-0] WARN  io.grpc.internal.ManagedChannelImpl - [Channel<5>: (pubsub.googleapis.com:443)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=No servers found for pubsub.googleapis.com:443, cause=null}
2022-06-23 19:46:26.105 [grpc-default-executor-0] ERROR n.d.b.g.c.nameresolver.DiscoveryClientNameResolver - No servers found for pubsub.googleapis.com:443
```

**Comment by kamalaboulhosn** [comment]
Eerrors of this nature can happen for many different reasons that are specific to each use case. In order to investigate an issue like this, we need more detailed information than can be provided in a GitHub issue. Please enter a support case if you experience this issue.

**Comment by salvatorenovelli** [comment]
Have the same problem, hopefully can contribute with a bit more information

Service running on a GCP VM, pulling messages from topics and then occasionally throwing the exception below. 
This is a spring boot application running Spring boot version 3.2.5 using  'org.springframework.boot' version '3.2.5'.

It's tricky to reproduce because it happens occasionally. While it's acceptable to have temporary network related failures, the fact that this happens on a background thread (my understanding) makes it hard to manage. eg: I wouldn't know how to flag the service as unhealthy to restart it automatically. (I assume there is one, but I've not found it, yet)



` io.grpc.internal.ManagedChannelImpl      : [Channel<7>: (pubsub.googleapis.com:443)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host pubsub.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: pubsub.googleapis.com: System error0)
ilc_1               |    at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:256)
ilc_1               |    at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213)
ilc_1               |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
ilc_1               |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
ilc_1               |    at java.base/java.lang.Thread.run(Unknown Source)
ilc_1               | Caused by: java.net.UnknownHostException: pubsub.googleapis.com: System error
ilc_1               |    at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
ilc_1               |    at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
ilc_1               |    at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
ilc_1               |    at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
ilc_1               |    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
ilc_1               |    at java.base/java.net.InetAddress.getAllByName(Unknown Source)
ilc_1               |    at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:640)
ilc_1               |    at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:388)
ilc_1               |    ... 5 more
`
